### ISSUE TITLE
♻️ `UserProviderFactory`가 다른 쿼리 메서드를 지원하도록 개선

### ISSUE THREAD

**Issue by uwoobeat** [FISOLUTION/fingerprint-backend#114]
## 📌 Description
- `findByLoginId` 외에도 다른 메서드를 처리할 수 있도록 개선합니다.

## 📝 To-do
- [ ] 로그인 쪽 관련해서 처리

**Comment by ChooSeoyeon** [comment]
그냥... 토큰을 id 말고 loginId로 생성하는 거 유지할까봐여,,ㅋㅋ 어차피 아이러빗이랑 하나의 서비스까진 아니여서 오히려 토큰이 다른게 나을 수도 있을 거 같습니다. 그렇게 된다면 당장엔 UsrProviderFactory가 다른 쿼리 메서드 지원할 필요 없습니다.

**Comment by ChooSeoyeon** [comment]
잠정 보류
