### ISSUE TITLE
✨ 신청서 목록 조회 시 신청시간 기준 내림차순 정렬하여 반환하도록 수정

### ISSUE THREAD

**Issue by uwoobeat** [FISOLUTION/fingerprint-backend#50]
## 📌 Description
- 

## 📝 To-do
- [ ] 
- [ ]

**Comment by ChooSeoyeon** [comment]
신청서에 baseTimeEntity 적용하신 후에, prod랑 dev db 둘다에 필드 추가 동일하게 해주세요!
